# Generated by Django 5.1.4 on 2025-01-16 20:21

import ipmanager.api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprange',
            name='value',
            field=models.CharField(
                max_length=32,
                validators=[ipmanager.api.models.validate_ipv4_or_cidr_address],
            ),
        ),
    ]
