# Generated by Django 5.2.9 on 2026-01-12 21:40
from django.db import migrations
from datetime import datetime, date
from zoneinfo import ZoneInfo
import re
from ipmanager.ui import apps
from django.contrib.auth.models import User
from django.db import migrations, models


known_users = {
        "BW": {
            "first_name": "Ben",
            "last_name" :"Wallberg",
            "username": "wallberg"
        },
        "KD": {
            "first_name": "Kate",
            "last_name" :"Dohe",
            "username": "katedohe"
    },
    }

def classify_user(user_model, initials):
    attrs = known_users[initials]
    user, created = user_model.objects.get_or_create(
        username = attrs ["username"],
        defaults = {
            "first_name": attrs ["first_name"],
            "last_name": attrs ["last_name"],
            "is_superuser": True,
            "is_staff": True,
            "is_active": True
    })
    return user 
       
def change_format(date):
    year, month, day = date.split('-')
    dt = datetime(int(year), int(month), int(day), tzinfo=ZoneInfo("America/New_York"))
    return dt

def split_notes(apps, schema_editor):
    group_model = apps.get_model('api', 'group')
    note_model = apps.get_model('api', 'note')
    user_model = apps.get_model('auth', 'user')
    
    for group in group_model.objects.all():
        for old_note in group.notes.split("; "):
            if match := re.match(r'(\w\w) (\d\d\d\d-\d\d-\d\d): (.*)', old_note):
                user_initials = match[1]
                date = match[2]
                content = match[3]
            elif match := re.match(r'(\d\d\d\d-\d\d-\d\d) (\w\w): (.*)', old_note):
                date = match[1]
                user_initials = match[2]
                content = match[3]
            elif match := re.match(r'(\d\d\d\d-\d\d-\d\d): (\w\w): (.*)', old_note):
                date = match[1]
                user_initials = match[2]
                content = match[3]
            elif match := re.match(r'(\d\d\d\d-\d\d-\d\d): (\w\w), (.*)', old_note):
                date = match[1]
                user_initials = match[2]
                content = match[3]
            else:
                continue
        
            timestamp = change_format(date)
            user = classify_user(user_model, user_initials)
            note = note_model(
                created=timestamp,
                user=user,
                group=group,
                content=content.strip()
            )
            note.save()

def delete_split_notes(apps, schema_editor):
    note_model = apps.get_model('api', 'note')
    note_model.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_note'),
    ]
    operations = [
        migrations.RunPython(split_notes, delete_split_notes),
    ]