# Generated by Django 5.2.9 on 2026-01-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_split_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='notes',
        ),
    ]
