# Generated by Django 5.2.9 on 2026-01-29 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_group_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
